# Generated by Django 2.2.2 on 2019-07-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abyss', '0002_auto_20190703_1915'),
    ]

    operations = [
        migrations.RenameModel('AbyssQuote', 'Quote'),
    ]
